ERROR2023-05-19 09:05:07,936D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-19 09:05:10,904D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-19 09:05:13,375D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-19 09:05:23,809D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-19 09:05:26,028D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-19 09:05:28,108D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-19 09:08:28,544D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-19.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
